// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjseqjhqsobqrmupdfqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indqc2Vxamhxc29icXJtdXBkZnFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODA4MTIsImV4cCI6MjA3MTQ1NjgxMn0.rXm_P0a-tp5NciCG6c_hgrN8h_tZ8YAshaDqJ15-_nE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});